#!/usr/bin/env bash

# i3lock-color lock-screen script for cribac-nordic theme
BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#81A1C1'
TEXT='#ECEff4'
WRONG='#BF616A'
VERIFYING='#B48EAD'

i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$WRONG         \
--bshl-color=$WRONG          \
\
--screen 1                   \
--image="${HOME}/.config/i3/scripts/cribac-nordic/lock-screen.png" \
--clock                      \
--indicator                  \
--time-str="%H:%M:%S"        \
--date-str="%A, %Y-%m-%d"    \
--keylayout 1                \

