# Inserts no blank line between shell prompts.
add_newline = false

# Define appearance of the "❯" symbol in the prompt.
[character] 
success_symbol = "[❯](bold #A3BE8C)"
error_symbol = "[✗](bold #bf616a)"

[directory]
truncation_length = 4
truncation_symbol = "…/"
style = "bold #88c0d0"
home_symbol = "[]"

# Disable the package module, hiding it from the prompt completely.
[package]
disabled = true
